### ISSUE TITLE
Return result as filesystem::path?

### ISSUE THREAD

**Issue by lethal-guitar** [dfranx/ImFileDialog#3]
This library looks really good, nice work! 👍🏻 And thanks for sharing the code. I'm considering switching to this one for my project.

While reading the API, I was wondering if you'd be open to providing the result as `std:: filesystem::path` instead of `std::wstring` (maybe via an additional function, like `GetResultPath` or similar)? The library is already using the filesystem header internally, after all. And having a `path` object would be nice for when you intend to do some more manipulation on the resulting path, or if you need the path as UTF-8 encoded string etc. The latter can be obtained easily via the `std:: filesystem::u8string` function, whereas it's more complicated to do with a `std::wstring`.

**Comment by dfranx** [comment]
Thank you so much!
I recoded part of the library so now the `GetResult()` method returns `std::filesystem::path`. This way you can easily obtain the UTF-8 encoded string. I've also completely switch from `std::wstring` to UTF-8 encoded strings internally so that Dear ImGui can properly display the filenames (issue #4).

**Comment by lethal-guitar** [comment]
Nice one! 👍🏻
