### ISSUE TITLE
Unicode support for file / folder result

### ISSUE THREAD

**Issue by alwendya** [dfranx/ImFileDialog#4]
Hi, first this work is amazing !
I'm French and using special character in filename like 'é' î' ...
When I open a file picker, the file name are not shown in totality, part are truncated where the special character is located  :
Exemple :
![image](https://user-images.githubusercontent.com/68951595/107760871-bfde4100-6d2a-11eb-9998-ac002f128362.png)
Here the folder name is '§Rangement à trier' and it shown '?rangement ?rier'.
I hope you can fix this because this file/folder browser is great.
If I can be of any help...

Grégory

**Comment by alwendya** [comment]
I managed to make a work around :
I'm putting my modified file attached to this post for information and I am well aware that's only working for windows but it give an hint of the way to proceed (And I don't know if the same happen from linux users for an example)...

I'm using these 3 function when text rendering happen or conversion between string/wstring using begin()/end() method which is unaware of utf8 string : 
-  to_utf8 (converting ansi string to utf8)
-  utf8_to_wstring (Converting utf8 string to wstring)
-  wstring_to_utf8 (converting wstring to ansi utf8)
[ImFileDialog.zip](https://github.com/dfranx/ImFileDialog/files/5972176/ImFileDialog.zip)

I'm looking now for a way to store the added quick access item to the software so that every time it is launched, quick access is re-populated...
And I don't figure how yet but having the dialog using system language would be nice too... (String table hard-coded maybe...)

Keep going ...
Grégory
PS: I try my best to write in english, I hope I'm understandable...

**Comment by dfranx** [comment]
Thank you for reporting this!

This should now be fixed with commit afbcf44 . I used `std::filesystem::path`'s `u8string()` method to get the UTF-8 encoded string. Dear ImGui should now be able to properly display the folder/file names.

PS: if you want to obtain the bookmarked directories, use the method `GetFavorites()`. You can then save the contents of the returned variable however you want to (it returns a vector of UTF-8 encoded `std::string`s). To add the bookmark, call `AddFavorite()` method. Both methods use UTF-8 encoded strings
